package Books::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Books::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:/home/dat/projects/Books/db/books.db',
        user => '',
        password => '',
        on_connnect_do => q{PRAGMA foreign_keys = ON},
    }
);

=head1 NAME

Books::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Books>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Books::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
